-- Safe to run repeatedly after the core migration.
insert into public.benefit_categories (id,name,color,icon,sort_order) values
('business','Business','#c8fa48','▦',1),('career','Career','#f0bc68','↗',2),('learning','Learning','#9f8aea','◆',3),
('travel','Travel','#f37e60','✦',4),('lifestyle','Lifestyle','#9fc8b4','◌',5),('local','Local','#79a7e8','⌂',6)
on conflict (id) do update set name=excluded.name,color=excluded.color,icon=excluded.icon,sort_order=excluded.sort_order;

insert into public.benefits (id,brand,title,category_id,label,member_value,color,text_color,description,eligibility,featured,status) values
('aws','aws','$5,000 in cloud credits','business','TECH','Up to $5,000','#c8fa48','#151613','Build, test and scale with startup-friendly cloud credits for eligible Foundry businesses.',array['founder'],true,'active'),
('qatar','QATAR\nAIRWAYS','20% off global flights','travel','TRAVEL','Up to 20% off','#f37e60','#ffffff','Access member-only fares across more than 170 destinations for business and personal travel.',array['founder'],true,'active'),
('wework','WEWORK','3 months workspace free','business','WORKSPACE','3 months free','#668fe9','#ffffff','Work flexibly from premium workspaces and business lounges in participating cities.',array['founder','employee'],true,'active'),
('canva','Canva','50% off Canva Teams','business','DESIGN','Save 50%','#b89cff','#201444','Create polished presentations, social content and team assets with premium design tools.',array['founder','employee','student','unemployed'],true,'active'),
('hyatt','HYATT','Complimentary room upgrade','travel','HOTELS','Free upgrade','#e7d2af','#3c2d18','Receive a complimentary room upgrade when available at participating properties.',array['founder'],false,'active'),
('selam','SELAM\nCOFFEE','Buy one, get one coffee','local','ADDIS PERK','Buy 1, get 1','#d99b6c','#3a1f0c','Meet, work or recharge with a complimentary second coffee at participating branches.',array['founder','employee','student','unemployed'],false,'active'),
('notion','Notion','6 months of Plus free','business','PRODUCTIVITY','6 months free','#dfe0db','#151613','Organize projects, documents, coursework and your professional portfolio in one place.',array['founder','employee','student','unemployed'],true,'active'),
('linkedin','LinkedIn','3 months Premium Career','career','CAREER','3 months free','#7eb6e8','#0b3155','Strengthen your profile, reach decision-makers and access advanced career insights.',array['founder','employee','student','unemployed'],false,'active'),
('coursera','COURSERA','40% off professional certificates','learning','LEARNING','Save 40%','#8ba7ee','#12214f','Build practical, verifiable skills with selected professional certificate programs.',array['employee','student','unemployed'],true,'active'),
('safaricom','SAFARICOM','Business data bundle bonus','business','CONNECTIVITY','25% extra data','#79c66a','#12320d','Keep your work connected with additional data on selected professional plans.',array['founder','employee'],false,'active'),
('wellness','THE\nWELL','25% off member wellness','lifestyle','WELLNESS','Save 25%','#9fc8b4','#153328','Access selected recovery, fitness and wellbeing services built for busy professionals.',array['founder','employee'],false,'active'),
('jobfair','TALENT\nROOM','Priority career room access','career','OPPORTUNITY','Priority entry','#f0bc68','#3c280a','Join curated employer rooms, CV clinics and interview-practice sessions before public release.',array['employee','student','unemployed'],true,'active')
on conflict (id) do update set brand=excluded.brand,title=excluded.title,category_id=excluded.category_id,label=excluded.label,member_value=excluded.member_value,color=excluded.color,text_color=excluded.text_color,description=excluded.description,eligibility=excluded.eligibility,featured=excluded.featured,status=excluded.status;

insert into public.events (id,title,organizer,event_type,summary,description,status,featured,start_at,end_at,rsvp_deadline,capacity,guest_policy,format,venue,address,latitude,longitude,map_label,cost_type,agenda,requirements,dress_code,age_restriction,accessibility,contact_email,contact_phone,eligibility,color,open_registration) values
('EVENT-FOUNDERS','Founder Leadership Roundtable','Foundry Community','networking','A small, candid room for founders navigating growth, hiring and capital decisions.','A moderated peer roundtable designed for practical exchange between company builders.','published',true,now()+interval '12 days',now()+interval '12 days 2 hours',now()+interval '10 days',28,'members-only','in-person','The Urban Center','Meskel Square, Addis Ababa',9.0108,38.7613,'The Urban Center','free','18:00 Arrival and introductions; 18:20 Moderated founder roundtable; 19:30 Peer connections and refreshments','Bring one current leadership challenge. A live Foundry membership card is required.','Smart casual','18+','Step-free access is available.','events@foundry.community','+251 911 000 101',array['founder'],'#151613',false),
('EVENT-COFFEE','Foundry Community Coffee','Foundry Community','social','Meet members from every part of the community over an easy Saturday coffee.','A relaxed gathering for introductions, conversation and community updates.','published',true,now()+interval '18 days',now()+interval '18 days 2 hours',now()+interval '17 days',80,'one-guest','in-person','Selam Coffee · Bole','Bole Road, Addis Ababa',8.9986,38.7904,'Selam Coffee · Bole','free','Open arrival, community welcome and member introductions.','Show your active Foundry membership QR at check-in.','Come as you are','None','Ground-floor venue with accessible entrance.','events@foundry.community','+251 911 000 101',array['founder','employee','student','unemployed'],'#d99b6c',true),
('EVENT-CAREER','Career Launch Lab','Foundry Talent Room','workshop','A hands-on CV, portfolio and interview workshop with local hiring leaders.','Practical career materials, peer feedback and recruiter guidance.','published',true,now()+interval '25 days',now()+interval '25 days 3 hours',now()+interval '23 days',60,'members-only','hybrid','Iceaddis','Bole Sub-City, Addis Ababa',9.0192,38.8125,'Iceaddis','free','CV clinic; portfolio review; interview practice; recruiter Q&A.','Bring a draft CV or portfolio.','Casual','16+','Live captions online and step-free venue access.','talent@foundry.community','',array['employee','student','unemployed'],'#8eafff',false),
('EVENT-WEBINAR','Digital Safety for Modern Teams','Foundry Learning','webinar','A practical online briefing on protecting accounts, teams and customer information.','A focused digital session covering account hygiene, access controls and incident response.','published',false,now()+interval '31 days',now()+interval '31 days 90 minutes',now()+interval '30 days',250,'members-only','online','','',null,null,'Online event','free','Threat overview; practical controls; response checklist; audience Q&A.','A stable internet connection and current browser.','','None','Live captions and a recording transcript.','learning@foundry.community','',array['founder','employee','student','unemployed'],'#9f8aea',false)
on conflict (id) do update set title=excluded.title,organizer=excluded.organizer,event_type=excluded.event_type,summary=excluded.summary,description=excluded.description,status=excluded.status,featured=excluded.featured,capacity=excluded.capacity,eligibility=excluded.eligibility,color=excluded.color,open_registration=excluded.open_registration;

insert into public.event_people (id,event_id,type,name,title,description,website,sort_order) values
('PERSON-ALMAZ','EVENT-FOUNDERS','host','Almaz Yohannes','Community Director · Foundry','Almaz designs founder programs and facilitates candid peer conversations.','',1),
('PERSON-SAMUEL','EVENT-FOUNDERS','speaker','Samuel Bekele','Founder · Blue Nile Ventures','Technology founder and early-stage investor focused on East Africa.','https://example.com',2),
('SPONSOR-SELAM','EVENT-COFFEE','sponsor','Selam Coffee','Community hospitality partner','Locally sourced Ethiopian coffee and welcoming community spaces.','https://example.com',1),
('PERSON-MERON','EVENT-CAREER','speaker','Meron Tadesse','People & Culture Lead','Meron helps growing teams build fair hiring systems.','',1)
on conflict (id) do update set event_id=excluded.event_id,type=excluded.type,name=excluded.name,title=excluded.title,description=excluded.description,website=excluded.website,sort_order=excluded.sort_order;

insert into public.admin_settings (id,settings) values ('community','{"community":{"communityName":"Foundry","timezone":"Africa/Addis_Ababa","membershipDuration":"12","reviewSla":"48","manualApproval":true,"hideDrafts":true}}') on conflict (id) do nothing;
